POST http://127.0.0.1:8000/signup Content-Type: application/json

{ "username": "serhii", "password": "qwerty123!", "email": "abc@mail.com" }

###

POST http://127.0.0.1:8000/login Content-Type: application/json

{ "username": "serhii", "password": "qwertу123!" }

###

GET http://127.0.0.1:8000/test_token Content-Type: application/json Authorization: token xxx