# Generated by Django 4.2.7 on 2023-11-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='welearn.user')),
                ('known_language', models.CharField(max_length=50)),
                ('desired_language', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
