# Generated by Django 4.2.7 on 2023-11-10 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0002_user_delete_customuser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='welearn.user')),
                ('known_language', models.CharField(max_length=50)),
                ('desired_language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default_password_value', max_length=128),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
