# Generated by Django 4.2.7 on 2023-11-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welearn', '0004_alter_languages_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='languages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
