# Generated by Django 4.2.7 on 2023-11-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welearn', '0005_languages_id_alter_languages_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
