# Generated by Django 4.2.7 on 2023-11-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0006_alter_languages_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=50)),
                ('desired_lang', models.CharField(max_length=50)),
                ('known_lang', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('last_time_pinged', models.DateTimeField(auto_now=True)),
                ('in_call', models.BooleanField(default=False)),
            ],
        ),
    ]
