# Generated by Django 4.2.7 on 2023-11-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welearn', '0007_peer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
