version: '3'
services:
  frontend:
    build:
      context: /workspace/Frontend_WeLearn
    ports:
      - "3000:3000"
  backend:
    build:
      context: /workspace/WeLearn_Back
    ports:
      - "8000:8000"
